# source: https://git.chalmers.se/courses/dit113/2024/group-2/dit-113-ci-workshop-group-2/ & https://codeblog.dotsandbrackets.com/gitlab-ci-esp32-arduino/

image: ubuntu:latest


before_script:
  # shell script installs arduino-cli dependencies and libraries
  - chmod +x setup-build-env.sh
  - ./setup-build-env.sh

stages:
  - build

compile:
  stage: build
  tags:
    - docker
  script:
    - echo "Wio Terminal compilation..."

    - export PATH=$PATH:/root/bin # set path to where arduino cli is installed
    - pwd                         # print working directory
    - cd src/wio-StuWi/src/stuwi_sketch_main # change directory to Wio Terminal source code folder

    - arduino-cli lib list                   # check that libraries are installed
    # compile
    - arduino-cli compile --fqbn Seeeduino:samd:seeed_wio_terminal



